[package]
name = "ezgl"
version = "0.4.0"
edition = "2021"

[dependencies]
glutin = { version = "0.31.3", features = ["wgl"] }
glow = "0.13.1"
raw-window-handle = "0.5.2"
winit = { version = "0.30.0", features = ["rwh_05"] }

[dev-dependencies]
env_logger = "*"
log = "*"
