[package]
name = 'ezgl'
version = '0.1.0'
edition = '2021'

[package.metadata.docs.rs]
features = ['winit']

[dependencies]
glutin = { version = '0.30.0-beta.2', features = ['wgl'] }
glow = '0.11.2'
raw-window-handle = '0.5.0'
winit = { version = '0.27.3', optional = true }

[features]
default = []
winit = ['dep:winit']

[dev-dependencies]
winit = '0.27.3'
env_logger = '*'
log = '*'
