name: Push
on: [push]

jobs:
  build:
    runs-on: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v5

    - name: Check without winit
      run: cargo check --all-targets

    - name: Check with winit
      run: cargo check --all-targets --all-features
